run:
  timeout: 5m
  go: "1.23"

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - gosec
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
